# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyopqt.ui'
#
# Created by: PyQt5 UI code generator 5.15.0 and M0g1)
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# qtchooser -run-tool=designer -qt=5 to launch qt designer
# pyuic5 -x filename.ui -o python_file_name.py

from PyQt5 import QtCore, QtGui, QtWidgets

from view.opengl.pyqt.myopengl_widget import MyOpenGLWidget


class Ui_MainWindow(object):
    def __init__(self):
        super().__init__()
        self.menubar = None
        self.menu_file = None
        self.action_save = None
        self.action_open = None
        self.menu_edit = None

        self.central_widget = None
        self.grid_layout = None
        self.verticalLayout = None
        self.openGL_widget = None
        self.label = None

        self.statusbar = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        size_police = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        size_police.setHorizontalStretch(30)
        size_police.setVerticalStretch(0)
        size_police.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(size_police)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.grid_layout = QtWidgets.QGridLayout(self.central_widget)
        self.grid_layout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        # ===========openGL widget======================================
        self.openGL_widget = MyOpenGLWidget(self.central_widget)
        self.openGL_widget.setMinimumSize(QtCore.QSize(780, 400))
        self.openGL_widget.setObjectName("openGLWidget")
        self.verticalLayout.addWidget(self.openGL_widget)
        self.grid_layout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        # =============label============================================
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setEnabled(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.grid_layout.addWidget(self.label, 1, 0, 1, 1)

        # =============horizontal layout=================================
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        # =============buttons===========================================
        self.pushButton_2 = QtWidgets.QPushButton(self.central_widget)
        self.pushButton = QtWidgets.QPushButton(self.central_widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.setObjectName("pushButton")

        def btn_act2() -> None:
            self.openGL_widget.is_draw ^= True
            print(f"open gl widget drawing is {self.openGL_widget.is_draw}")
            self.openGL_widget.update()

        # def btn_act() -> None:
        #     self.label.setText("Button clicked")

        self.pushButton.clicked.connect(btn_act2)
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.grid_layout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        MainWindow.setCentralWidget(self.central_widget)
        # ================upper menu==================================
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menuFile")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menuedit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("actionOpen")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("actionSave")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_save)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Text Area"))
        self.pushButton_2.setText(_translate("MainWindow", "Create Sphere"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_edit.setTitle(_translate("MainWindow", "edit"))
        self.action_open.setText(_translate("MainWindow", "Open"))
        self.action_save.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
